version: 2
default_assignees: ["mateuszkwiecinski"]
updates:
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "gradle"
      directory: "buildSrc"
      schedule:
          interval: "daily"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
