name: After merge build

on:
  push:
    branches:
      - master
      - main
      - trunk
      - develop
      - maine
      - mane
  schedule:
    - cron: '0 3 * * 1,4'

jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleGraphqlRelease assembleMockedRelease

      - name: Assemble debug
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleGraphqlDebug

      - uses: actions/cache@v2
        name: Upload base (release)
        with:
          path: |
            diffuse-source-file-release
            diffuse-mapping-file-release
          key: diffuse-${{ github.sha }}-${{ hashFiles('**/apk/graphql/release/**.apk') }}

      - run: cp app/build/outputs/apk/graphql/release/app-graphql-release-unsigned.apk diffuse-source-file-release
        shell: bash

      - run: cp app/build/outputs/mapping/graphqlRelease/mapping.txt diffuse-mapping-file-release
        shell: bash

      - uses: actions/cache@v2
        name: Upload base (debug)
        with:
          path: diffuse-source-file-debug
          key: diffuse-${{ github.sha }}-${{ hashFiles('**/apk/graphql/debug/**.apk') }}

      - run: cp app/build/outputs/apk/graphql/debug/app-graphql-debug.apk diffuse-source-file-debug
        shell: bash
