name: Build project

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('buildSrc/*.kt') }}
        restore-keys: |
            gradle-
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Code style check
      run: ./gradlew projectCodestyle
    - name: Assemble
      run: ./gradlew assembleGraphqlRelease assembleMockedRelease
    - name: Unit tests
      run: ./gradlew test
    - name: Android Lint
      run: ./gradlew lint
