name: Build project

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - name: Cache .gradle
      uses: burrunan/gradle-cache-action@v1
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Code style check
      run: ./gradlew projectCodestyle
    - name: Assemble
      run: ./gradlew assembleGraphqlRelease assembleMockedRelease
    - name: Unit tests
      run: ./gradlew test
    - name: Android Lint
      run: ./gradlew lint
