name: Generate dependency diff

on:
  pull_request:
    branches:
      - master

jobs:
  generate-diff:
    env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - name: Cache .gradle
      uses: burrunan/gradle-cache-action@v1
    - id: dependency-diff
      name: Generate dependency diff
      uses: mateuszkwiecinski/dependency-tree-diff-action@master
      with:
        configuration: graphqlReleaseRuntimeClasspath
    - uses: peter-evans/find-comment@v1
      id: find_comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: Dependency diff
    - uses: peter-evans/create-or-update-comment@v1
      with:
        body: |
          Dependency diff: 
            ```
            ${{ steps.dependency-diff.outputs.text-diff  }}
            ```
        edit-mode: replace
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        token: ${{ secrets.GITHUB_TOKEN }}