name: Build project

on:
  pull_request:

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    env:
      github_token: ${{ secrets.token }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Codestyle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: projectCodestyle
          dependencies-cache-enabled: true

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleGraphqlRelease assembleMockedRelease
          dependencies-cache-enabled: true

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          dependencies-cache-enabled: true

      - name: Android Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint
          dependencies-cache-enabled: true
