name: Build project

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    env:
      github_token: ${{ secrets.token }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 24

      - uses: gradle/actions/wrapper-validation@v4

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew projectCodestyle

      - run: ./gradlew assembleGraphqlRelease assembleMockedRelease

      - run: ./gradlew projectTest

      - run: ./gradlew projectLint

      - run: ./gradlew check --scan

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            app/build/**/*.apk
            app/build/**/mapping.txt
