name: Build project

on:
  pull_request:

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  build:
    env:
      github_token: ${{ secrets.token }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew projectCodestyle

      - run: ./gradlew assembleGraphqlRelease assembleMockedRelease

      - run: ./gradlew projectTest

      - run: ./gradlew projectLint

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            app/build/**/*.apk
            app/build/**/mapping.txt
