name: Update Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: usefulness/update-gradle-wrapper-action@master
        with:
          set-distribution-checksum: false
          git-user-name: "Mateusz Kwiecinski"
          git-user-email: "36954793+mateuszkwiecinski@users.noreply.github.com"
